version: '3'
services:
  app:
    build: 
      context: .
    env_file:
      - .env.docker
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: new-disk_db
